### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by AzhamProdLive** [AzhamProdLive/Notes_App_Nothing#1]
- [x] GridView
- [ ] pin 📍 nodes
- [ ] Archive notes
- [ ] Google account support

If you want to suggest a feature to add to this project, please write it as a comment on this issue. Suggestions outside of this issue will be discarded.

**Comment by I-AQ** [comment]
- [ ] To do list
- [ ] HTML text input
